### ISSUE TITLE
Redmine 3.3 compatibility?

### ISSUE THREAD

**Issue by mr-gosh** [altsol/redmine_mattermost#12]
Documentation says it is not compatible with [Redmine 3.3](http://www.redmine.org/projects/redmine/wiki/Download) - is this the fact?
What could be done to bounce it to the newest version?
If wrong - the documentation should be upgraded..

**Comment by thanosk** [comment]
Hello @mr-gosh, truth is I haven't tested it yet. It should run, though, as I'm not aware of any Redmine API changes. If you manage to test it yourself, let me know. For the documentation, you're right, the proper thing is to upgrade it but until I test it myself, I prefer to be on the safe side.

**Comment by thanosk** [comment]
Hello again @mr-gosh, redmine compatibility with 3.3.x was tested and documentation got updated, thanks for your feedback!

**Comment by mr-gosh** [comment]
thanks! awesome!
