### ISSUE TITLE
customized routing to different Groups not possible?

### ISSUE THREAD

**Issue by mr-gosh** [altsol/redmine_mattermost#16]
we have different groups in our Mattermost instance.

How can i route redmine messages to a channel in another group than the default one?
can these IDs be used that are present in newer Mattermost Instances?

**Comment by thanosk** [comment]
Hello, have you tried using a project custom field named "Mattermost URL" (without quotes) on a per-project basis? 1st in your mattermost setup, you will generate all the "Incoming WebHook" URLs you need. Secondly, in redmine you will assign these different hook urls on a per-project basis.

**Comment by mr-gosh** [comment]
so this is necessary for different teams on the same mattermost instance?
--Edit--
I now set up the "Mattermost URL" Custom field but recognized that i now have to enter this URL in EVERY Project.

It would be much better to have a default URL set in the Plugin and if the "MAttermost URL" Field is filled - than this different URL will be used...

**Comment by thanosk** [comment]
This is exactly how this works. The default URL setting can be found in Redmine -> Administration -> Plugins -> Redmine Mattermost (click Configure button to the right). Fill this URL and the channel below it as the default settings and it will work for all projects as default/global values. Then, for each project that you want different behaviour, you can fine-tune on a per-project basis via their own custom field settings.

**Comment by mr-gosh** [comment]
THX - it indeed works!
