### ISSUE TITLE
Per-project mattermost url

### ISSUE THREAD

**Issue by lafriks** [altsol/redmine_mattermost#18]
If you have single redmine for multiple mattermost team, this plugin can be used for only one team as there is no way to specify custom mattermost url on per-project basis

**Comment by lafriks** [comment]
Looked in source code there and there is such option so closing issue, it is just missing info in wiki

**Comment by thanosk** [comment]
You can specify a custom mattermost url on a per-project basis. Yes, it's not mentioned in the README, but if you take a look in the plugin configuration page inside Redmine, it lets you know, it's the same thing with the channel per-project custom field.
