### ISSUE TITLE
Method channels_for_project broken for nested Redmine projects

### ISSUE THREAD

**Issue by tobenschmidt** [altsol/redmine_mattermost#20]
The method `channels_for_projects` is supposed to return a flat array with one or more channel names as items like `["redmine"]`. If you have nested Redmine projects it returns nested arrays like `[["redmine"]]` or `[[["redmine"]]]` because of the recursive calls of `channels_for_project` and the multiple call of the `split` method:
```ruby
val = [
    (proj.custom_value_for(cf).value rescue nil),
    (channels_for_project proj.parent),
    Setting.plugin_redmine_mattermost[:channel],
].find{|v| v.present?}
[...]
val.split(",")
```

This leads to an error in the incoming webhook of Mattermost: 
> Unable to parse incoming data

Update: I don't use a custom field for the channel name.

Update 2: The initial description was wrong in some parts. I fixed this.

**Comment by thanosk** [comment]
@tobenschmidt thank you for your contribution!
