### ISSUE TITLE
"Version" field's id is shown on Mattermost, not its name

### ISSUE THREAD

**Issue by Jdecaudin** [altsol/redmine_mattermost#22]
I've a Redmine's issue with "Version" field valued by "4.2" and identified by "9".

On Mattermost, when the issue is changed via Redmine, the text displayed is : 

> Version source
> 9

Expected : 

> Version source
> 4.2

**Comment by thanosk** [comment]
Hello @Jdecaudin, please help me reproduce this bug. Are you talking about the "Target Version" default redmine field or a custom one? If it is a custom one, can you please share its exact setup ?

**Comment by Jdecaudin** [comment]
Hello @thanosk,
My bad, it's a custom field with : 

- Format : version
- multi valued : False
- status : all
- tag style : list
- requiered : false
- all projects : true
- visible : for all
- Trackers : all

**Comment by thanosk** [comment]
Thank you @Jdecaudin for your feedback!
I was able to reproduce and confirm the bug. I commited a patch for it, when you find the time to test it, let me know if it solves the problem.

**Comment by Jdecaudin** [comment]
Many thanks @thanosk this patch fixes the problem.
I close the Issue.
