### ISSUE TITLE
Redmine 3.1.1.stable.14669 + MM 3.7.0: Notifications missing from certain user.

### ISSUE THREAD

**Issue by bor8** [altsol/redmine_mattermost#25]
Please put in README.md that your user does not have

`I don't want to be notified of changes that I make myself`

checked in `My account`, otherwise you won't get updates from this user in your Redmine channel in Mattermost!

**Comment by thanosk** [comment]
@bor8 are you sure of this? I just run a test switching all possible redmine notification options on and off and that didn't produce the result you are describing, thus updates in the mattermost always arrive. Are you sure you're not experiencing another issue perhaps?

**Comment by bor8** [comment]
Yes, for me it helped to uncheck this setting. I am 90 % sure in my setting, with plugins:

Plugin+URL | Author | Version
-- | -- | --
Computed custom field                          https://github.com/annikoff/redmine_plugin_computed_custom_field | Yakov Annikov | 0.0.3
Redmine Agile plugin (PRO version)             Scrum and Agile project management plugin for redmine             http://redminecrm.com | RedmineCRM | 1.3.11
Redmine Checklists plugin (Light version)             This is a issue checklist plugin for Redmine             http://redminecrm.com | RedmineCRM | 3.1.3
Redmine Mattermost             Mattermost chat integration             https://github.com/altsol/redmine_mattermost | AltSol | 0.6
Private Wiki             Adds private pages to wiki | Oleg Kandaurov | 0.2.1
Redmine Slack             Slack chat integration             https://github.com/sciyoshi/redmine-slack | Samuel Cormier-Iijima | 0.2
