### ISSUE TITLE
Image and name used in redmine is not reflecting in mattermost

### ISSUE THREAD

**Issue by ebinmanuval** [altsol/redmine_mattermost#37]
I configured the mattermost and redmine as per the documentation but in Mattermost it is using my image and name instead of redmine configuration 
Redmine Configuration 
![image](https://user-images.githubusercontent.com/7802869/95851454-4b3acc00-0d63-11eb-912a-e18cd693b530.png)
MatterMost Notification
![image](https://user-images.githubusercontent.com/7802869/95851531-660d4080-0d63-11eb-8720-fce02303f74c.png)

**Comment by thanosk** [comment]
There are a couple of switches and settings inside Mattermost that could go wrong.
One is located at System Console -> Integrations -> Integrations Management -> Enable integrations to override usernames, you need to set that as true.
Another is located at Integrations -> Incoming Webhooks -> Edit your specific one -> There is a username textfield there, make sure it's not set.

I can produce some screenshots of the above setup if that would help, let me know if you need that.

**Comment by ebinmanuval** [comment]
Thank you for your help, it worked. I didn't find this information in the README file.
