### ISSUE TITLE
Problems with the work of the Matthermost plug-in

### ISSUE THREAD

**Issue by AnnSoldatova** [altsol/redmine_mattermost#40]
Good afternoon, I have a problem with the Matthermost plugin for my redmine. It stopped working on October 1. I guess this is due to the deprecation of the InedTrust root certificate. On the machine where Redmine is installed, the operating system is Centos 7.6.1810.
Uploaded a new list of root certificates, including GlobalSignRootCA_R3, the certificate on the matthermost server from letsencrypt. I would be grateful for your help in resolving this issue, thank you in advance.

**Comment by thanosk** [comment]
@AnnSoldatova This specific problem is not related in any way with this plug-in. However, here are a few, hopefully helpful, resources:

1. https://letsencrypt.org/2021/10/01/cert-chaining-help.html
2. https://blog.devgenius.io/rhel-centos-7-fix-for-lets-encrypt-change-8af2de587fe4
3. https://aws.amazon.com/premiumsupport/knowledge-center/ec2-expired-certificate/
4. just google for: centos 7 let's encrypt root certificate

**Comment by ashish1099** [comment]
@thanosk the problem is infact with the ruby working with httpclient, it does not read the OS default ca cert and in my case I had to tell the httpclient that this is a ca cert path and then it started working with it.
