### ISSUE TITLE
No Notifications for issues created or edited via e-mail

### ISSUE THREAD

**Issue by erSitzt** [altsol/redmine_mattermost#5]
Hi,

we are creating issues from emails via imap like this:

```
rake --trace redmine:email:receive_imap RAILS_ENV="production" \
    host=mailserver username=user password=pass \
    project=project1 \
    tracker=tracker1 \
    folder=Redmine \
    unknown_user=accept \
    default_group=employee \
    no_account_notice=1 \
    no_permission_check=1 \
    allow_anonymous=1 \
    allow_override=tracker,priority,status
```

This does not create a user in redmine and the tickets are created by "anonymous" which does not seem to trigger the plugin to send a notification to mattermost.

regards
Dennis

**Comment by thanosk** [comment]
I edited this issue title because the bug affects creating or updating issues via e-mail in general for both eponymous and anonymous users.

@erSitzt I've also commited some changes that I believe resolve this issue. Could you please test and confirm that everything's ok?

**Comment by erSitzt** [comment]
Thanks, i'll test and report back !

**Comment by erSitzt** [comment]
It's working thanks !
