### ISSUE TITLE
Custom fields in tickets are not saved if mattermost plugin is active

### ISSUE THREAD

**Issue by erSitzt** [altsol/redmine_mattermost#7]
If it helps, the problem does not occur with [redmine_telegram](https://github.com/ANemcov/redmine_telegram) plugin

**Comment by thanosk** [comment]
Patch commited, can you test it please?

**Comment by rroseselavy42** [comment]
Initial testing looks good, have not been able to recreate the problem with subtasks

**Comment by erSitzt** [comment]
Will do when i am at work tomorrow !

**Comment by erSitzt** [comment]
Looks good !
