### ISSUE TITLE
Subtasks and other fields cause internal server errors when Post Issue Updates?" is enabled

### ISSUE THREAD

**Issue by rroseselavy42** [altsol/redmine_mattermost#8]
backtrace:

```
pp 6609 stderr: Completed 500 Internal Server Error in 172ms (ActiveRecord: 50.3ms)
App 6609 stderr: 
App 6609 stderr: NoMethodError (undefined method `user' for nil:NilClass):
App 6609 stderr:   lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
App 6609 stderr:   lib/redmine/hook.rb:61:in `each'
App 6609 stderr:   lib/redmine/hook.rb:61:in `block in call_hook'
App 6609 stderr:   lib/redmine/hook.rb:58:in `tap'
App 6609 stderr:   lib/redmine/hook.rb:58:in `call_hook'
App 6609 stderr:   app/models/issue.rb:175:in `create_or_update'
App 6609 stderr:   app/models/issue.rb:1509:in `recalculate_attributes_for'
App 6609 stderr:   app/models/issue.rb:1467:in `update_parent_attributes'
App 6609 stderr:   app/models/issue.rb:175:in `create_or_update'
App 6609 stderr:   app/controllers/issues_controller.rb:482:in `block in save_issue_with_child_records'
App 6609 stderr:   app/controllers/issues_controller.rb:470:in `save_issue_with_child_records'
App 6609 stderr:   app/controllers/issues_controller.rb:180:in `update'
App 6609 stderr:   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
App 6609 stderr: 
App 6609 stderr: 
```

```
Environment:
  Redmine version                3.1.2.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [i386-linux-gnu]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
  GitRemote                      2.1.4
Redmine plugins:
  clipboard_image_paste          1.8
  redmine_git_remote             0.0.1
  redmine_mattermost             0.3
  redmine_stealth                0.6.0
  redmine_wiki_extensions        0.7.0
```

**Comment by rroseselavy42** [comment]
only consistent thing is when trying to update a subtask

**Comment by ngmdat** [comment]
I have same error yesterday (Mar.14) after installing this plugin.
some thing wrong about ":journal => self.current_journal"

> ```
>   def save_from_issue
>     self.reload
>     if not @create_already_fired
>       Redmine::Hook.call_hook(:redmine_mattermost_issues_edit_after_save, { :issue => self, :journal => self.current_journal})
>     end
>     return true
>   end
> ```

**Comment by thanosk** [comment]
I've come up with a minor patch for this (nil check), could you please try it out?

**Comment by rroseselavy42** [comment]
Initial testing looks good, have not been able to recreate the problem with subtasks

**Comment by rroseselavy42** [comment]
Spoke too soon, found when doing a right click and changing task status

```
App 31726 stderr: Completed 500 Internal Server Error in 190ms (ActiveRecord: 12.4ms)
App 31726 stderr: 
App 31726 stderr: NoMethodError (undefined method `scan' for nil:NilClass):
App 31726 stderr:   lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
App 31726 stderr:   lib/redmine/hook.rb:61:in `each'
App 31726 stderr:   lib/redmine/hook.rb:61:in `block in call_hook'
App 31726 stderr:   lib/redmine/hook.rb:58:in `tap'
App 31726 stderr:   lib/redmine/hook.rb:58:in `call_hook'
App 31726 stderr:   app/models/issue.rb:175:in `create_or_update'
App 31726 stderr:   app/controllers/issues_controller.rb:292:in `block in bulk_update'
App 31726 stderr:   app/controllers/issues_controller.rb:278:in `each'
App 31726 stderr:   app/controllers/issues_controller.rb:278:in `bulk_update'
App 31726 stderr:   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
App 31726 stderr: 
App 31726 stderr: 
```

**Comment by ngmdat** [comment]
Hi altsol, thanks for your support.
500 Internal Server Error was fixed, but Mattermost doesn't get message from Redmine.
Then, if i change code as following: 

   def speak(msg, channel, attachment=nil, url=nil) 
        ...
        params[:username] = username if username
        # params[:channel] = channel if channel
        ...

Mattermost can get message from Redmine. How about working of channel ?
And How about working of "Mattermost Icon" ?

**Comment by thanosk** [comment]
@rroseselavy42 I cannot reproduce any error when editing the issue and changing its properties (including its status). Make sure you're on the latest version of this plugin, I pushed another changeset yesterday. You mentioned "doing a right click", are you using some kind of desktop client perhaps? (for all my tests I'm using redmine's web interface, but I can test another client if it is feasible).

@ngmdat Mattermost receives messages from Redmine after the latest fixes, are you sure your setup is configured properly? Pay extra attention when configuring Mattermost Webhooks and this plugin, you need to configure using the channel special handle, not the channel name (for example, for messages to go to OffTopic, the channel handle is off-topic). The Mattermost icon setting is the avatar to be used in Mattermost, it works by leaving the default value as is, but you can customize it if you need a different avatar.

**Comment by rroseselavy42** [comment]
@thanosk I did apply the patch and it does fix the issue with subtasks. When I say right click I mean in the web interface. I did some more testing and it seems to happen with bulk updates.

**Comment by thanosk** [comment]
@rroseselavy42 Thanks for clarifying it was during bulk updates, I reproduced it and pushed another fix for it.
